#!/usr/bin/env python

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shiva.settings")
django.setup()

# your imports, e.g. Django models
from django.contrib.auth.models import User
User.objects.create_superuser('developer', 'developer@shiva.com', 'fuinho-violento')


