# Generated by Django 3.0.5 on 2020-05-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type your name.', max_length=256, verbose_name='Name')),
                ('phone', models.CharField(blank=True, help_text='Type your phone.', max_length=256, null=True, verbose_name='Phone')),
                ('email', models.EmailField(help_text='E-mail for contact.', max_length=70, verbose_name='E-mail')),
                ('type', models.CharField(choices=[('0', 'Help'), ('1', 'Helper')], default='1', help_text='Are you an angel?', max_length=6, verbose_name='Type')),
                ('item_type', models.CharField(choices=[('0', 'Food'), ('1', 'Medical'), ('2', 'Shelter'), ('3', 'Utils/Clothes')], default='1', help_text='What is it that you have/need?', max_length=6, verbose_name='Item Type')),
                ('note', models.TextField(help_text='Type a note.', null=True, verbose_name='Note')),
                ('country', models.CharField(help_text='Type your country.', max_length=256, verbose_name='Country')),
                ('city', models.CharField(help_text='Type your city.', max_length=256, null=True, verbose_name='City')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Type a reason.', verbose_name='Reason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=24)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='ticket_app.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
