# Generated by Django 3.0.5 on 2020-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('0', 'Need help?'), ('1', 'Can help?')], default='1', help_text='Are you an angel?', max_length=6, verbose_name='Type'),
        ),
    ]
