# Generated by Django 3.0.5 on 2020-05-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_auto_20200520_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(help_text='Type your state.', max_length=60, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city',
            field=models.CharField(help_text='Type your city.', max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='country',
            field=models.CharField(help_text='Type your country.', max_length=60, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, help_text='Type your phone.', max_length=30, null=True, verbose_name='Phone'),
        ),
    ]
