# Generated by Django 3.0.5 on 2020-05-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_auto_20200521_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
