# Generated by Django 3.0.5 on 2020-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_auto_20200522_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='alert_me',
            field=models.BooleanField(default=True, help_text='Get E-mail notifications for new tickets?', verbose_name='Notifications'),
        ),
    ]
